// <auto-generated />
namespace Bus_Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sp_getByScheduleId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_getByScheduleId));
        
        string IMigrationMetadata.Id
        {
            get { return "202101210250373_sp_getByScheduleId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
