// <auto-generated />
namespace Bus_Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sp_ExtractBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_ExtractBD));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201708560_sp_ExtractBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
